### ISSUE TITLE
Allow Client to Create Admin Account - Pricing

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#1]
## Summary

Need to iron out the plan options. We give them a free trial period (14 Day), lets talk about whether or not this goes into V1. No need for a reminder - its on the user to cancel
while registering, the admin should be shown the license key in some manner (for your records here is your license key)

Our pricing plans should be based on purchasing X number of licenses
Show percentage complete
(possibly, while signing up - the chatbot could ask the user if they need to be contacted)

**IMPORTANT:** We need to guard against the end users sharing the license key to multiple people.

## Requirements

**SCENARIO:** New user is registering with our system for the first time
GIVEN as an unregistered user
WHEN I navigate to the login screen
THEN I see a link to sign up

GIVEN the unregistered user is signing up
WHEN they are registering
THEN they must fill out the following organization information:

- First Name *
- Last Name *
- Organization Name *
- Email Address *
- Phone Number

GIVEN the unregistered user has completed the form
WHEN they hit 'Next'
THEN the system should validate the data
AND if the validation passes they should move on
AND if the validation fails they should be required to fix the data

GIVEN as an unregister user has completed the account information form
WHEN validation passes
THEN they must select a service plan

GIVEN as an unregistered user
WHEN i am selecting my service plan
THEN a third party payment processor will be presented to the user
AND they should complete the payment form

GIVEN the payment information has been entered
AND the payment information processed successfully
WHEN the user hits 'Submit'
THEN the system should send a welcome email with the account details

GIVEN as an unregistered user
WHEN I see the welcome email
THEN I click link to active account (email confirmation)
AND the user should be auto-logged in

## Tasks

- [ ] [Create Login Page for Admin/Non Admin Users (UI)](https://github.com/profundli/donorai-mobile/issues/4) 
- [ ] Style Login Page
- [ ] [Create Sign-up/Profile Page for Admin/Non Admin Users (UI)](https://github.com/profundli/donorai-mobile/issues/5)
- [ ] Style Sign-up/Profile Page
- [ ] [Setting up Auth Provider for Account Authentication and Creation](https://github.com/profundli/donorai-mobile/issues/6)
- [ ] [Enabling Role's and Permissions for Users (UI)](https://github.com/profundli/donorai-mobile/issues/7)
- [ ] [Save and View Role's and Permissions for Users (Back end)](https://github.com/profundli/donorai-mobile/issues/7)
