### ISSUE TITLE
Allow User to View/Edit Dashboard

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#10]
Number of donors in stewardship vs (# of recurring donors that donated within the past 365 days)

## Requirements
**SCENARIO:** Dev Officer Should Be Able To View The Top 5 Leads/Donors
GIVEN the dev officer logs into the system
WHEN they view their dashboard
THEN they should see a list of Leads

GIVEN a dev officer is viewing the dashboard
WHEN they see the list of leads
THEN the list should be prioritized based on the date/time of associated task, most recent first

**SCENARIO:** Dev Officer Should See Their Calendar Of Events From The Dashboard
GIVEN a registered user has logged into the system
WHEN they log in
THEN they should be able to see a 'View Calendar' option

GIVEN the registered user is logged in
WHEN they click on View Calendar
THEN they should be able to see events in a calendar view

GIVEN the registered user sees the calendar view
WHEN they click on an event
THEN they should be able to change the event data
AND update the event

**NOTE** This should be daily, maybe weekly for dashboard

**Scenario:** Dev Officer Needs To Be Able To See Total Raised On The Dashboard
GIVEN a registered user has logged into the system
WHEN they log in
THEN they should see a metric for Total Raised

**Note**
for MVP we need to display on the dashboard the individual Total Raised
this will reset annually Jan 1 - Dec 31. Donor Increase Number and Percentage Change from previous year
Donor Differential

GIVEN a registered user has logged into the system
WHEN they log in
THEN they should see a metric for Donor Differential

how many NEW donors have you moved from cultivation to stewardship. this should look back over the last 365 days and calculate. this will change on a daily basis because of the sliding window. this should be compared to the past year using the same date range.

we need to display this at a dev officer level and also have the ability to roll this number out at the organization level

## Tasks
Create a dashboard with the following views:
- [ ] **Top 5 Leads** - Prioritized based on the date/time of associated task, most recent first

### Sample Lead Data

| First Name  | Last Name | Organization | Stage |
| ------------- | ------------- | ------------- | ------------- |
| John  | Smith  | Proctor and Gamble | Cultivation |
| Sally | Field | Mcdonalds | Stewardship |
| Frank | Thomas  | MLB | Cultivation |
| Butch  | Cassidy  | Parker Brothers | Cultivation |
| Bob | Hope  | Deloitte | Cultivation |

- [ ] **Top 5 Tasks** - this is correlated with Top 5 Leads

### Sample Task Data

| Task Type   | Touch Type | Contact Name | Due Date | Status |
| ------------- | ------------- | ------------- | ------------- |  ------------- |
| Meeting  | Coffee w/ CEO  | John Smith | 10/27/19 | In Progress |
| Networking  | Home Gathering  | Sally Field | 10/28/19 | Complete|
| Donation Request | Donation  | Frank Thomas | 10/29/19 | In Progress |
| Meeting  | Group Tour  | Butch Cassidy | 10/30/19 | In Progress |
| Networking  | Gayla Event  | Bob Hope | 10/31/19 | In Progress |
- [ ] **Calendar Preview** - Displayed on dashboard with event data or tasks. This can be Daily, Weekly or monthly views.

### Sample Calendar Preview Images. These are just suggestions but open to other suggestions.

![image](https://user-images.githubusercontent.com/54555846/67626516-f6c8d480-f811-11e9-8dc1-43fa1c5cc627.png)
- [ ] **Total Donations Raised** - Total Donations Raised for the current calendar year between Jan 1 - Dec 31.
- [ ] **Donor Differential** - Total NEW donors that transitioned from "Cultivation" to "Stewardship" starting from the current date/time to the last 365 days. This value is divided by the previous 365 days to calculate the percentage value.

- Figma Wireframe: https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=80%3A0

**Comment by cdprofundli** [comment]
Added Figma wireframe :https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=80%3A0

Note 2 different layouts one is a table based top 5 and the other is a card based top 5
