### ISSUE TITLE
Update Billing and Account Information

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#14]
SCENARIO: A system admin is editing billing
GIVEN a system admin is logged into the system
WHEN they navigate to the admin section
THEN they should see an option to Edit Billing

GIVEN the admin clicks on Edit Billing
THEN the system should provide some UI that allows the user to see their current billing information
AND the user should be able to edit the following:

Change Credit Card
Change Service Plan (upgrade/downgrade or cancel)
Change Billing Address
GIVEN the system administrator is changing the credit card
WHEN they click on 'Edit Credit Card'
THEN they should be able to enter a new credit card
AND it should be processed through the 3rd party processor

GIVEN the system admin is changing the service plan
WHEN they click on 'Change Service Plan'
THEN the user should be presented with the service plans
AND the system should indicate what plan they currently are on
AND the user can select a new plan

GIVEN the system admin is Changing the service plan
WHEN they are upgrading to a higher service plan
THEN the user should be able to select the new plan
AND the payment information should be billed at this time
AND the system should inform the user they will be charged

GIVEN the system admin is Changing the service plan
WHEN they are downgrading services
THEN the system should check to ensure they don't have to many users for the lower plan
AND if they pass this check
THEN the system should downgrade them
AND the system should not charge them less until the next billing period

GIVEN the system admin is Canceling Services
WHEN the system admin presses Cancel Services
THEN the system should present the user with a 'Confirmation Of Cancellation'
AND if the user confirms
THEN the system should remain active for the remainder of the billing period
AND at the end of that billing period they should no longer be able to log in.

## Tasks ## 

- [ ] Create a menu option for edit billing to manage subscriptions and billing information for the organization.
- [ ] Under the edit billing menu, the following information should be displayed:
- Update Credit Card Information
- Update Service Plan (upgrade/downgrade or cancel)
- Update Billing Address
- [ ] Under the Credit Card menu option, the admin should be able to update the payment method such as updating their credit card information or third party payment information.
- [ ] Under Billing address section, they should be able to update their billing address.
- [ ] Under the service plan section, they should be able to change (upgrade or downgrade) or cancel.
