### ISSUE TITLE
System Admin to Configure Engagement Matrix

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#15]
## Description ## 

* an engagement matrix is a list of touches performed by the Dev officers
* we need to define a Default list of touches that ships with the system.

## Requirements ##

Engagement Matrix Options 

__Intimate Touches__
* coffee
* private tour
* tour
* coffee with CEO
* lunch
* dinner

__Non-Intimate Touches__
* follow up
* gift
* attending an event

*Automatic Engagements* - automatic but ability to opt lead/donor out (another card)
* newsletter
* annual report
* e-blasts

SCENARIO: the system administrator is configuring the organizations Engagement Matrix

GIVEN the system admin is logged into the system
WHEN they navigate to the admin section
THEN they should see an option for 'Configure Engagement Matrix'

GIVEN a system admin clicks on 'Configure Engagement Matrix'
THEN they should be able to Add, Edit or Remove engagement types

GIVEN the system admin is Adding engagement types
WHEN they click Add
THEN the system should provide some UI that allows the system admin to enter the new type

Fields
* Title
* Description

GIVEN the system admin is Editing an engagement type
WHEN the system admin clicks on the engagement type
THEN the system should provide some UI for editing the current data
AND the system should obsolete the current one
AND the system should create the new engagement type for use

GIVEN the system admin is Removing an engagement type
WHEN the system admin clicks on the engagement type
THEN the system should provide some UI for removing the current engagement option
AND the system should obsolete this engagement type

## Tasks ## 

- [ ] Create a sub menu option for "Configuring Engagement Matrix", which will list all touch types for given tasks.
- [ ] There should be a list of touch type options as follows. There should be a title and description explaining each touch type:
- coffee
- private tour
- tour
- coffee with CEO
- lunch
- dinner
- newsletter
- annual report
- e-blasts
- [ ] There should be options to add, update, delete or make engagement types obsolete.

**Comment by cdprofundli** [comment]
Figma link
https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=189%3A0
