### ISSUE TITLE
User (Non admin and admin) to Configure their Email and Calendar provider (gmail, outlook, etc) to sync with Internal Calendar

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#16]
## Requirements ##

GIVEN a registered dev officer logs into the system
WHEN the dev officer navigates to Edit Profile
THEN they should see an option to Configure/connect email/calendar

GIVEN that a registered user has navigated to their profile
WHEN they click Configure
THEN the user should see a list of providers to configure

GIVEN the registered sees the list of providers
WHEN they select a provider to configure
THEN the system should redirect them to that providers domain
AND the user should choose the account to configure

GIVEN that the registered user has redirected to the providers system
WHEN they select the account to configure
THEN the there should appear an authorization screen to allow access to that domain

GIVEN that the registered user has selected the account to configure
WHEN they select authorize for that account
THEN the provider should automatically allow the application to connect to that domain
AND the user would be redirected back to the application

## Tasks ## 

- [ ] Create a menu option for "Configuring Email/Calendar" Provider.
- [ ] Create a field or dropdown for selecting the email and calendar provider such as exchange or gmail
- [ ] Once provider has been selected, then the user should be redirected to that provider's domain.
- [ ] User should be able to select the account from that provider to sync with the application's email and calendar. This will require authorization between the two applications.
- [ ] User will be redirected back to application after authorization has been completed. This will pull in existing data from calendar and email and also allowing future bidirectional syncing between application and provider
