### ISSUE TITLE
Configure Email templates based on Category for Automation of Tasks

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#17]
## Requirements ##

**Types of Tasks.** 

* Phone call/text
* Introduction
* Follow up
* Reminders
* Event Task/Information (sending to donor inviting them to an event, not on your calendar)
* Meeting (in a separate story)
* Networking

**Types of Email Template Touches**
* coffee
* private tour
* tour
* coffee with CEO
* lunch
* dinner
* follow up
* gift
* attending an event
* newsletter
* annual report
* e-blasts

SCENARIO: Dev officer is logged in and configuring their email templates

GIVEN that a registered user logs into the system
WHEN they navigate to their edit profile
THEN they should see a section for Manage Email Templates

GIVEN navigates to edit profile
WHEN they click on the Manage Email Templates option
THEN they should have to select an action

GIVEN the registered user selects Edit
THEN the user should have to select a Task Type

GIVEN the registered user is updating an email template
WHEN they click on the Task Type 
THEN they will need to select a Touch associated with that type

GIVEN the registered user has selected a Task Type 
AND a Touch
THEN the system should provide the email template for edit
 

SCENARIO - Adding a new template

GIVEN a registered user is adding a new email template
WHEN they login 
AND navigate to their profile
THEN they should be able to select Add Template

GIVEN a registered user click Add Template 
THEN the user should be required to enter a Task Type
AND  the user should be required to enter a Touch 
AND the user should be able to type out an email/template for this combination
AND they hit save

## Tasks ## 

- [ ] Create a menu option for "Manage Email Templates".
- [ ] There should be a list of Email Template Types that are categorized by Task Type.
- [ ] There should be a list of Email Template Types that are also categorized by Touch Type, which are children of Task Types.
- [ ] When the user clicks on each Task Type, Email Templates will be filtered by all Touch Types within that Task Type.
- [ ] When user clicks on individual Touch Type, email templates should be filtered by Touch Type and Task Type
- [ ] System admins should be able to add/update/delete email templates from Task and Touch Types

**Comment by cdprofundli** [comment]
Figma link
https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=318%3A0
