### ISSUE TITLE
Allow Dev Officer To Import a Lead

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#19]
###### Adding Lead Data

GIVEN a registered user logs into the system
WHEN they view their dashboard
THEN the dev officer should see "+" icon to add a Lead

GIVEN a dev officer logs into the system
WHEN they click on the 'Add Lead' button
THEN the system should present the user with a form to create the lead

GIVEN the dev officer clicks on 'Add Lead'
WHEN the system shows the form
THEN the assign field should be pre-populated for that dev officer

GIVEN the dev officer clicks on 'Add Lead' 
WHEN system shows the form 
THEN the user should be able to assign any user to that lead

GIVEN the dev officer clicks on Add Lead 
WHEN they complete the form
THEN the system should save this new lead

###### Updating Lead Data
GIVEN a dev officer logs into the system
WHEN they search for a lead
OR navigate to a leads profile
THEN they should be able to click 'Edit Lead' 

GIVEN the dev officer navigates to the leads profile
WHEN they click Edit Lead
THEN the user should be able to edit the leads data
AND save the record

##### SCENARIO: the dev officer is adding a lead/donor by scanning a business card.

GIVEN a registered user clicks on '+' icon to add a lead
WHEN they can view the new lead profile screen
THEN the dev officer should an option to scan business card

GIVEN a registered user sees the scan business card option
WHEN they click on the option
THEN the users camera should be opened 

GIVEN a registered user accessed their camera
WHEN they take a picture of potential lead's business card
THEN the system should automatically scan the text on the card

GIVEN a registered user can take a picture of potential lead's business card
WHEN the system scans the text on the card
THEN the system should display a preview of the data scanned

GIVEN the system has scanned the data
WHEN the user sees the scanned text
THEN they should be able to edit the preview
AND identify any incorrect fields

GIVEN the data has been scanned 
AND all data in the preview is correct
WHEN the user hits Save
THEN the system should save the new lead.

__Fields We Know Of__
* FirstName
* LastName
* Email
* Phone
* Organization
* Address - hook into google maps
* Assignee (Dev Officer)

__ RESOLUTION__ 

the connector must be in the system before they can be added as a connector
remove/hide/disable the Recommended By Field when first entering a lead this becomes active once they are in cultivation -since we are hiding the field i took it off the list of fields we know.

### Tasks 

- [ ] Create floating actionable button (FAB) on dashboard screen to trigger opening the new lead profile screen
- [ ] Allow editable fields on lead profile screen before saving form data
* FirstName
* LastName
* Email
* Phone
* Organization
* Address - hook into google maps
* Assignee (Dev Officer)
- [ ] Add a button the allow user to scan lead's business card using OCR to automatically populate data on the form fields.
- [ ] Add appropriate validation to form fields before submitting form. If validation fails, then an error message should be displayed based on required fields input data.
- [ ] Transition screen from editable to non editable state once the user clicks save and submit button
- [ ] Add calls to back-end service to create, read, update lead information

Figma Design:
https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=409%3A92

**Comment by cdprofundli** [comment]
Figma link for importing a lead manually or with scan
https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=744%3A13

**Comment by cdprofundli** [comment]
Added Organization options, notes with priorities, and add not from ended phone call
