### ISSUE TITLE
Allow User to Associate Corporation as a Lead

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#20]
##### Associating a lead to a corporation
GIVEN a development officer is entering a lead 
AND the corporation doesn't exist in the system
THEN the development officer will click on 'Add Corporation'

GIVEN the corporation does not exist in the system
WHEN the dev officer clicks on Add Corporation
THEN the system will take them to a form to enter the corporation data

GIVEN the dev officer enters the corporation data
WHEN they save the record
THEN the system will navigate them back to the lead screen

GIVEN the dev officer is entering a lead 
AND the corporation exists in the system 
WHEN the dev officer is entering the data 
THEN they should select the corporation from a list

GIVEN the dev officer navigates back to the lead screen 
THEN the dev officer will fill out the rest of the leads profile data
AND press Save

#### Creating a corporation as a lead
1. when you are entering a lead , first name, last name, corporation 
    * if the corporation does not exist in the system the user will enter that corp data at that time
    * if the corporation does exist they user will select it from a drop down while entering data

2. when you are entering leads and its a corporation, we will need to present the user with a different screen to enter that corporation data and the corporation will be treated as a lead.

__the main difference__ is that in the first scenario the corporation would not show on your board as a potential lead. the second scenario, the corporation would show up as a potential lead. 

__Note__: think about web crawling for the name as the user is entering data. Find the corporation based on the input from the user. maybe we can accomplish this with an input field and if the entry is in the database we show it otherwise we give a 'search' and it would perform a crawl.

### Tasks 

- [ ] Add a searchable drop-down component on the add new lead profile screen to add or associate a corporation (organization) as a lead to the individual lead profile screen
- [ ] Allow editable fields on lead profile screen before saving form data
* Organization Name
* Email
* Phone
* Address - hook into google maps
* Assignee (Dev Officer)
- [ ] Add appropriate validation to form fields before submitting form. If validation fails, then an error message should be displayed based on required fields input data.
- [ ] Transition screen from editable to non editable state once the user clicks save and submit button
- [ ] Add calls to back-end service to create, read, update lead organization information

### Figma
https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=744%3A381
