### ISSUE TITLE
Allow user to initiate an email to Lead Manually

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#24]
GIVEN that a registered user has navigated to a leads profile
WHEN they have selected a lead
THEN they should see an option to email the lead

GIVEN that the registered user has selected a leads profile
WHEN they click the option to email the lead
THEN the system should provide an email form

GIVEN the registered user clicks the option to email the lead
WHEN the system provides email form
AND the user fills it out
THEN clicks Send
THEN the email should be sent

### Tasks 

- [ ] Create a button called "Send Email" that will trigger opening screen to create new email screen, which should be an email editor.
- [ ] Note: May need to default to email client on phone, if provider isn't set up or display error message that email provider is not set up.
- [ ] Allow user to send email and should be synced up with email provider the application's internal email client. To be defined in another story.
