### ISSUE TITLE
Management needs the ability to add notes to Dev Officers Leads/Donors

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#25]
GIVEN a manager logs into the system
WHEN they view their dashboard
THEN they should see a high level view of their Dev Officers workload

GIVEN the manager views the Dev officers workload 
WHEN they click on the Dev Officer
THEN they should be able to see the Dev officers current lead list

GIVEN the manager sees the lead they want to enter notes for
WHEN they click on a lead
THEN they should see an option to Add Notes

GIVEN the manager sees the option for adding notes
WHEN they press the option 
THEN they should be able to enter notes 
AND hit save

### Tasks 

- [ ] Manager can view screen of dev officers that are currently reporting to that manager
- [ ] Manager can drill down on dev officer and view currently leads under that dev officer
- [ ] Manager clicks on lead or donor and can see an option to "Add Notes"
- [ ] Manager clicks button to add notes and allows them to enter text then click save.
