### ISSUE TITLE
All Users Need ability to search/filter for a Contact

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#26]
#####SCENARIO: A user has logged in and viewing their landing page and performing a lead/donor
GIVEN a user has logged in
WHEN the user navigates to the landing page
THEN there should be a menu option to access leads screen

GIVEN a user has navigated to the leads screen
WHEN there is search bar located at the top
THEN the user should be able to key in a lead's First Name and Last Name

GIVEN a user has located the search bar at the top
WHEN the user keys in the lead's First Name and Last Name
THEN system should return search results of multiple Leads based off of First Name and Last Name

GIVEN a user has entered the lead's First Name and Last Name in the search bar
AND there are search results returned
WHEN they select a Lead from the results
THEN the system should redirect them to the Lead's Profile that was selected

### Tasks 

- [ ] Create a search/filtering option for leads that is accessible for the leads screen
- [ ] Leads should be filterable by first name / last name or additional key criteria
- [ ] Organizations should also be filterable since they can be a lead as well

### Figma
https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=535%3A9
