### ISSUE TITLE
Dev Officer should be able to view/edit the lifecycle of a lead

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#27]
Lead pipeline where you can see the status of Introduction,Cultivation,Stewardship,Closed

GIVEN a registered user
WHEN they access the donor-pipeline view
THEN they should see a kanban style view of their leads

GIVEN that a dev officer is viewing their Donor Pipeline View
WHEN the potential lead has been imported
THEN the potential lead should appear in the introduction stage

__INTRODUCTION__
GIVEN that the lead appears in the Introduction stage
WHEN the dev officer has created a follow up task
OR the dev officer does a manual move from Introduction -> Cultivation
THEN the system should change the status of that lead to Cultivation

__CULTIVATION__
GIVEN that the lead appears in the Cultivation stage
WHEN the donor donates
THEN the dev officer should be able to move that donor to the Stewardship
AND the status should be updated to Stewardship

__STEWARDSHIP__
GIVEN the donor is in Stewardship for a period of time
WHEN the donor is no longer donating
THEN the dev officer should be able to 'Close' the donor's profile

__QUESTION WE HAD__
how do we handle the scenario where the dev officer has many leads/donors in a certain step.

__RESOLUTION__
LLyas made the statement that the user will need to manage their own data. 
this management combined with the new alerts we just defined it will cover the scenario where donors are in stewardship for a long time.

### Tasks 

- [ ] Create a Kanban style view that allows contacts to be categorized in three different stages (Introduction, Cultivation and Stewardship)
- [ ] Each contact should at least contain the first and last name and possibly other key information.
- [ ] Allow the ability to drag and drop contacts between all three categories
- [ ] The "Introduction" stage, which is officially a "Lead" will be set when a new contact is imported as a lead
- [ ] The "Cultivation" stage , which is officially an "Opportunity" will be set when a dev officer has triggered a follow-up meeting task to meet with a potential donor.
- [ ] The "Stewardship" stage will be set when a donation has been established. This will close the current "Opportunity".
- [ ] The contact can remain in "Stewardship" phase, as they can donate on a recurring basis. After they have initially donated, they have graduated from "potential donor" to "donor". This will open up a new "Opportunity" for future donations.
- [ ] More details regarding how tasks trigger lifecycle stages will be included in the Tasks epics
- [ ] A contact can also be set to a "Closed" status but will not appear in the contact pipeline.

### Figma
https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=588%3A47

**Comment by cdprofundli** [comment]
Do we want these stages to be updated on the contact details page too?
