### ISSUE TITLE
Dev Officer Needs to be able to Add/Edit Tasks

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#29]

**Comment by profundli-admin** [comment]
##### SCENARIO: User is navigating to task list for Add/Edit
GIVEN a registered user has logged in
WHEN viewing the dashboard 
THEN they should see an option to view 'Task List'

GIVEN a registered user sees the 'Task List' option
WHEN they click on it
THEN they should be navigated to the Task List

GIVEN the registered user clicks on their Task List 
WHEN they have navigated to their task list
THEN they should see a list of all their tasks

##### SCENARIO: user has navigated to task list and is adding a task
GIVEN the registered user has navigated to their task list 
WHEN they see a list of all their tasks
THEN they should see an option for 'Add Task'

GIVEN the user sees an option to 'Add Task'
WHEN they click on the option
THEN they should see an Task Details screen

GIVEN the user has clicked on Add Task
WHEN they see the Task Details screen
THEN they should be able to edit the fields

GIVEN the user enters the data into the fields 
WHEN the form validates
THEN the user should see an option for 'Save'

GIVEN the user enters valid data 
WHEN they hit 'Save'
THEN the system should save the new task.

##### SCENARIO: user has navigated to task list and is editing a task
GIVEN the registered user has navigated to their task list 
WHEN they see a list of all their tasks
THEN they should be able to click on an existing task

GIVEN the user has clicked on an existing task 
WHEN they click on the task
THEN the system should display the Task Details screen 

GIVEN the user has clicked on a task for Edit 
WHEN they see the Task Details screen
THEN they should be able to update the data fields

GIVEN the user has entered data into the field 
WHEN the form validation passes
THEN the system should update the task 

GIVEN a user is creating a task 
WHEN they have selected the Task Type
AND Touch Type
THEN the system should provide an email preview 

GIVEN the user sees the preview
WHEN the preview is generated
THEN the system will pre-populate the email body from template based on the type of Task 
AND the Touch Type

GIVEN the user sees the preview
WHEN the preview is generated
THEN the system will pre-populate other email fields  (To, From,Subject, CC, BCC)

GIVEN the user sees the preview
WHEN the preview is generated
THEN the system will pre-populate token replacement fields in the body of the email (Lead/Donor Name, Location)

**THESE ARE EVENTS NOT TASKS - its a domain driven step that happens in the application - audit log** - Break these out in their own separate story
 - Phone Calls 
 - Text
 - Email

###Note: 
we need to add events (like phone calls) as a task on this story. refer back to zube 49



### THESE ARE TASKS - A task is assigned unit of work that has not yet been completed, which also is recorded in your calendar**

* Meeting: When you select meeting this is going to display the touch type field. Meeting tasks are typically created for greeting of following-up with a lead/opportunity. This would include engagement types. This information will be pulled in shortly. The first meeting invite (Greeting) sent to that lead should move the lead from Lead To Opportunity.

* Networking Event: This applies to either a schedule or unscheduled event where would meet potential leads. This occurs prior to any meeting tasks (greeting/follow-up). No engagement types that apply to Networking events. The touch type field disappears when this type of task is selected. The following fields will be displayed. Networking just exists on your calendar. This could prompt user to add lead as well if you just met someone.

* Donation Request: (single vs multi year as well). This occurs typically after you follow-up with an opportunity and you are ready to move to them to a donor. Once they have donated, then the task is closed and they move to donor phase.  If donation amount is recorded, then close task out and move to donor stage. If no donation amount recorded, enter the reason and the contact either remains opportunity or removed entirely from pipeline. This is no Touch Type.

### Reminders: 

Reminders are properties of any type of task, not a task. There should be an option to suppress reminders in a task. Otherwise reminders are automatic for a given a task on their calendar. Push notifications are an option that also tied to suppression option. Also, if an alert is received, there should be an option to suppress alert it directly versus editing task.

NOTE: Reminders are going to be part of a separate story and not associated with tasks. the option to suppress will be at the reminder level not the task level. 


### Tasks 

- [ ] Dev Officer will navigate from the following screens in order to view the task workflow screen:
   - Top 5 Tasks (view all Tasks)
   - From Main Menu
- [ ] After Dev Officer can access the options above, then the dev officer should be able to access the Task workflow screen with a list of all assigned tasks
- [ ] Dev Officer should see an option to "Add Task" and select that option it will trigger the task details screen with the following details for Meeting Task.  There should be a save option to create/update the task and validation for invalid data. Fields to add:
   - Type of Task
   - Touch Type
   - Start date - (automatically populate with date but overridable for future dates) 
   - Due Date (date of meeting)
   - Priority
   - Status (Not Started, In-progress, Completed)
   - Assignee
   - Contact Name
   - Location
   - Subject
   - Body
   - Attachments
   - From
   - To
   - CC
   - BCC
- [ ] Dev Officer should see an option to "Add Task" and select that option it will trigger the task details screen with the following details for Networking Task.  There should be a save option to create/update the task and validation for invalid data. Fields to add:
   - Type of Task
   - Start date - (automatically populate with date but overridable for future dates) 
   - Due Date (date of meeting)
   - Priority
   - Status (Not Started, In-progress, Completed)
   - Assignee
   - Location
- [ ] Dev Officer should see an option to "Add Task" and select that option it will trigger the task details screen with the following details for Donation Request Task.  There should be a save option to create/update the task and validation for invalid data. Fields to add:
   - Type of Task
   - Start date - (automatically populate with date but overridable for future dates) 
   - Due Date (date of meeting)
   - Priority
   - Status (Not Started, In-progress, Completed)
   - Assignee
   - Contact Name
   - Donation Method (online, check, gala, stock options, campaign)
   - Link to donation site (Url to make payment)
   - Donation amount (if there is no donation, field for entering reason would appear)
   - Donation Details (Comments field for any details about donation)
   - Recurring Task (Option which will allow quarterly (3 month), semi-annual (6 month), annual (12 month) reminder to request donation)
   - Subject
   - Body
   - Attachments
   - From
   - To
   - CC
   - BCC
- [ ] For certain types of tasks (needs additional clarification), based on the Task Type and and Engagement, an email preview screen will appear on the Task Details screen. The following details will appear:
   - An pre-generated email template will appear based on the Task Type and Touch Type
   - Email specific fields such as the following will be pre-populated based on manual entry in the task details 
   - To, From,Subject, CC, BCC
   - The system will pre-populate token replacement fields such as Lead/Donor Name, Location. These will be variables in the template that will be replaced with values from the task details screen. More details to come based on associated template.

## Figma wireframe ##
https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=646%3A5

### Notes
we need to incorporate zube ticket 54 into this story.

**Comment by cdprofundli** [comment]
Figma link:
https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=646%3A5

This one should be good to go for base wireframe with all options

**Comment by cdprofundli** [comment]
Updated Date and Time
