### ISSUE TITLE
Non-Admin Registers their Account

### ISSUE THREAD

**Issue by profundli-admin** [profundli/donorai-mobile-ui#8]
## Summary:

Show percentage complete
POSSIBLE FUTURE DEV

Possibly, while signing up - the chatbot could ask the user if they need to be contacted

## Requirements
**Scenario:** new non-admin user is registering with DonorAI and must complete profile
GIVEN as a new user that has just confirmed email
WHEN I click the link in the email
THEN I am logged into the system
AND taken to my profile for completion

**Scenario:** Unregistered user is signing up on the registration form
GIVEN the unregistered user is signing up
WHEN they are registering
THEN they must fill out the following information:
- First Name *
- Last Name *
- Email Address *
- Phone Number - opt
- Username * (pre-populate with email address but should be editable)
- Password *

**Scenario:** New non-admin user has entered all their information and saves
GIVEN as a new non-admin user
WHEN I click on Save
THEN my profile should be updated
AND I should be taken to the landing page

## Tasks

- [ ] [Create/Style Login Page](https://github.com/profundli/donorai-mobile/issues/4)
- [ ] [Create/Style Sign-up/Profile Page](https://github.com/profundli/donorai-mobile/issues/5)
- [ ] [Setting up Auth Provider](https://github.com/profundli/donorai-mobile/issues/6)
- [ ] [Enabling Role's and Permissions for Users](https://github.com/profundli/donorai-mobile/issues/7)

## Figma
https://www.figma.com/file/yAre7ANwMapev6LV8QquTm/DonorAi?node-id=813%3A0
